name: Push to CMS
on:
  workflow_dispatch:
    inputs:
      problems:
        description: 'File path. Ex. "Day1/Sample"'
        default: ''
        type: string
      first:
        description: 'first push to CMS?'
        default: false
        type: boolean
jobs:
  run:
    uses: tw20000807/cms-actions/.github/workflows/push-to-cms.yml@main
    with:
      problems: ${{ inputs.problems }}
      first: ${{ inputs.first }}